---
dp_id: 0x0000000000000003   # The id of the datapath to be controlled
name: "Edge 3" # The name of the datapath for use with logging
description: "Edge 3"    # Purely informational
hardware: "??"
monitor_ports: True # whether gauge should monitor stats for ports
monitor_ports_file: "ports.out" # The file to record ports statistics
monitor_ports_interval: 10  # the polling interval for port stats in seconds
monitor_flow_table: True    # whether gauge should take periodic flow table dumps
monitor_flow_table_file: "ft.out"   # the file to record flow table dumps
monitor_flow_table_interval: 10 # the polling interval for flow table monitoring
influxdb_stats: True
interfaces:
    2:
        name: "core 2"   # name for this port, used for logging/monitoring
    1:
        name: "core 1"
    4:
        name: "core 4"
    3:
        name: "core 3"
    5:
        name: "C"
