dp_id: 0x0000000000000002   # The id of the datapath to be controlled
name: "ARP-1" # The name of the datapath for use with logging
description: "SDX ARP Switch"    # Purely informational
hardware: "??"
monitor_ports: True # whether gauge should monitor stats for ports
monitor_ports_file: "ports.out" # The file to record ports statistics
monitor_ports_interval: 10  # the polling interval for port stats in seconds
monitor_flow_table: True    # whether gauge should take periodic flow table dumps
monitor_flow_table_file: "ft.out"   # the file to record flow table dumps
monitor_flow_table_interval: 10 # the polling interval for flow table monitoring
influxdb_stats: True
interfaces:
    1:
        name: "Main"
    2:
        name: "Route Server"
    3:
        name: "ARP Proxy"
